### ISSUE TITLE
Frontend Night #32

### ISSUE THREAD

**Issue by yamadayuki** [wantedly/frontend-night#33]
- 資料の準備をがんばらない
- 参加・途中退席は自由
- スキップしない

2018/05/10 19:00~20:00

話したい・聞きたいネタを書いてく ✏️

ハッシュタグ [#frontend_night](https://twitter.com/hashtag/frontend_night?src=hash)

**Comment by yamadayuki** [comment]
https://user-first.ikyu.co.jp/entry/goodbye-jquery
一休.comホテルページのスマホ版からjQuery依存を取り除くためにやったこと
エンジニア

**Comment by yamadayuki** [comment]
https://github.com/npm/tink

**Comment by stomk** [comment]
https://goodpatch.com/work/hands-lab?lng=ja

**Comment by stomk** [comment]
https://twitter.com/natfriedman/status/1084888939112980480

**Comment by KentoMoriwaki** [comment]
https://github.com/denoland/deno が進化してる話

**Comment by KentoMoriwaki** [comment]
https://inside.pixiv.blog/tawachan/6254
