### ISSUE TITLE
Frontend Night #40

### ISSUE THREAD

**Issue by yamadayuki** [wantedly/frontend-night#41]
- 資料の準備をがんばらない
- 参加・途中退席は自由
- スキップしない

2019/03/29 19:00~20:00

話したい・聞きたいネタを書いてく ✏️

ハッシュタグ [#frontend_night](https://twitter.com/hashtag/frontend_night?src=hash)

**Comment by KentoMoriwaki** [comment]
https://github.com/atlassian/react-beautiful-dnd

**Comment by yamadayuki** [comment]
https://wasi.dev/

**Comment by KentoMoriwaki** [comment]
https://hacks.mozilla.org/2019/03/standardizing-wasi-a-webassembly-system-interface/
https://www.fastly.com/blog/announcing-lucet-fastly-native-webassembly-compiler-runtime
