### ISSUE TITLE
[08/01] Frontend Night

### ISSUE THREAD

**Issue by KentoMoriwaki** [wantedly/frontend-night#52]
- 資料の準備をがんばらない
- 参加・途中退席は自由
- スキップしない

2019/08/01 19:00~20:00

話したい・聞きたいネタを書いてく ✏️

ハッシュタグ [#frontend_night](https://twitter.com/hashtag/frontend_night?src=hash)

**Comment by KentoMoriwaki** [comment]
## Chrome 76

https://blog.chromium.org/2019/06/chrome-76-beta-dark-mode-payments-new.html

**Comment by KentoMoriwaki** [comment]
## Changelog of React 16.9

https://github.com/facebook/react/pull/16254

**Comment by KentoMoriwaki** [comment]
## The Layout Instability API

https://web.dev/layout-instability-api

**Comment by kobayang** [comment]
## When to useMemo and useCallback
https://kentcdodds.com/blog/usememo-and-usecallback
