### ISSUE TITLE
[08/29] Frontend Night

### ISSUE THREAD

**Issue by chloe463** [wantedly/frontend-night#56]
- 資料の準備をがんばらない
- 参加・途中退席は自由
- スキップしない

2019/08/29 19:00~20:00

話したい・聞きたいネタを書いてく ✏️

ハッシュタグ [#frontend_night](https://twitter.com/hashtag/frontend_night?src=hash)

**Comment by kobayang** [comment]
`react-axe` 導入してみた

https://github.com/wantedly/visit-admin-frontend/issues/701

**Comment by saitoeku3** [comment]
Auth0 の SPA 向け SDK が刷新されていた
https://auth0.com/blog/jp-introducing-auth0-single-page-apps-spa-js-sdk/
