### ISSUE TITLE
[09/19] Frontend Night

### ISSUE THREAD

**Issue by kdnk** [wantedly/frontend-night#58]
- 資料の準備をがんばらない
- 参加・途中退席は自由
- スキップしない

2019/09/19 19:00~20:00

話したい・聞きたいネタを書いてく ✏️

ハッシュタグ [#frontend_night](https://twitter.com/hashtag/frontend_night?src=hash)

**Comment by kobayang** [comment]
## Storybook 5.2

https://medium.com/storybookjs/storybook-5-2-794958b9b111

- DocsPage 
- MDX(experimental)
- Component Story Format
  - `storiesOf` を書かなくて良くなった。

**Comment by chloe463** [comment]
## GraphQL と JWT の話

https://blog.hasura.io/best-practices-of-using-jwt-with-graphql/#basics_client_setup
