### ISSUE TITLE
[10/03] Frontend Night

### ISSUE THREAD

**Issue by kdnk** [wantedly/frontend-night#59]
- 資料の準備をがんばらない
- 参加・途中退席は自由
- スキップしない

2019/10/03 19:00~20:00

話したい・聞きたいネタを書いてく ✏️

ハッシュタグ [#frontend_night](https://twitter.com/hashtag/frontend_night?src=hash)

**Comment by kdnk** [comment]
https://phabricator.wikimedia.org/phame/live/7/post/175/wikipedia_s_javascript_initialisation_on_a_budget/?utm_source=Perf.email&utm_campaign=38feea3ddf-EMAIL_CAMPAIGN_2019_09_23_03_45&utm_medium=email&utm_term=0_7cba5dc7bd-38feea3ddf-1248858173

**Comment by kdnk** [comment]
https://github.com/wantedly/profile/issues/20

**Comment by kdnk** [comment]
Techniques to make a web app load fast, even on a feature phone

https://web.dev/load-faster-like-proxx/
https://twitter.com/kosamari/status/1176147394490060806

**Comment by kobayang** [comment]
## Announcing TypeScript 3.7 Beta

https://devblogs.microsoft.com/typescript/announcing-typescript-3-7-beta/
